#!/usr/bin/env bash
# Write index.md, the homepage of https://btclib.org/, from
# btclib-org/.github's profile/README.md at the commit named on the
# command line.
#
# That file is the organization's page: it is what github.com/btclib-org
# renders, and it introduces the organization and indexes the
# repositories. The site says the same thing, so one of the two is
# written and the other derived -- a transcription is the copy that goes
# stale, which is the rule tests/copyright_test.py of btclib-org/.github
# already follows in deriving a lint pattern from COPYRIGHT rather than
# restating it.
#
# The body written below is the source's bytes and nothing else. That is
# what makes the result auditable in one command by anybody, without
# knowing what this script does:
#
#   awk 'n>=2 {print} $0=="---" {n++}' index.md \
#     | cmp - <(curl -fsSL "$RAW/<the commit index.md records>/$PATH")
#
# so a transformation added here -- a rewritten link, a stripped
# heading -- takes that property away and is not a small change.
#
# The commit is an argument and not `main`, and the argument is the whole
# of the pin: index.md records it, homepage.yml's verify job re-derives
# at it, and a hand edit to the file is then the difference between two
# byte strings rather than a claim about who touched what. Deriving from
# `main` instead would move the answer under every open pull request --
# a change landing in btclib-org/.github would turn this repository's
# checks red on branches that had not touched anything.
#
# What is refused rather than rewritten is a link destination that is not
# absolute. github.com resolves a relative destination against the
# repository the file sits in and Jekyll resolves it against the site
# root, so the same text is two different links; every destination in the
# source is absolute today, and the refusal is what keeps that a property
# rather than a coincidence. Rewriting them here was the alternative, and
# it fails the paragraph above: the body would no longer be the source's
# bytes.

set -euo pipefail

# the target is written relative to the repository root, so the script
# answers the same wherever it is invoked from
cd "$(dirname "$0")/../.."

RAW=https://raw.githubusercontent.com
REPOSITORY=btclib-org/.github
SOURCE=profile/README.md
TARGET=index.md

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <commit of $REPOSITORY>" >&2
    exit 2
fi
commit=$1

# forty hex digits, because a branch or a tag is a name its owner can
# move and this one is written into a file as the answer to "which text
# is this". `git ls-remote https://github.com/btclib-org/.github main`
# is where a caller gets one
if ! printf '%s' "$commit" | grep -qE '^[0-9a-f]{40}$'; then
    echo "$0: '$commit' is not a full commit sha" >&2
    exit 2
fi

body=$(curl -fsSL "$RAW/$REPOSITORY/$commit/$SOURCE")

# every link destination the file carries: the inline form, and the
# reference definition form that markdownlint's MD053 would otherwise be
# the only reader of. Refused unless it names a scheme or is a fragment
# of this same page -- those two are what the renderers agree about
destinations=$(
    printf '%s\n' "$body" \
        | grep -oE '\]\([^)]*\)|^ {0,3}\[[^]]+\]: *[^ ]+' \
        | sed -Ee 's/^\]\(//' -e 's/\)$//' -e 's/^ {0,3}\[[^]]*\]: *//'
)
relative=$(printf '%s\n' "$destinations" | grep -vE '^([a-z][a-z0-9+.-]*:|#)' || true)
if [ -n "$relative" ]; then
    echo "$0: $SOURCE carries a destination that is not absolute," \
         "which github.com and Jekyll resolve differently:" >&2
    printf '%s\n' "$relative" >&2
    exit 1
fi

# `layout` is the only key Jekyll reads here; the rest is the pin and the
# notice. A YAML comment is invisible to a reader of the rendered page,
# which is why it says what it says to a reader of the file -- the one
# place a hand edit would be made
{
    echo '---'
    echo '# Generated by .github/scripts/derive-homepage.sh, and not'
    echo '# written here: this file is btclib-org/.github'"'"'s'
    echo '# profile/README.md at the commit below, under front matter.'
    echo '# An edit made here is what homepage.yml refuses; what to do'
    echo '# instead is CONTRIBUTING.md'"'"'s "Changing the homepage".'
    echo 'layout: default'
    echo "source_repository: $REPOSITORY"
    echo "source_path: $SOURCE"
    echo "source_commit: $commit"
    echo '---'
    printf '%s\n' "$body"
} > "$TARGET"
